export const airports = [
  // New York Area Hubs
  {
    code: "JFK",
    city: "New York",
    country: "United States",
    name: "John F. Kennedy International Airport",
    lat: 40.6413,
    lng: -73.7781,
  },
  { code: "LGA", city: "New York", country: "United States", name: "LaGuardia Airport", lat: 40.7769, lng: -73.874 },
  {
    code: "EWR",
    city: "Newark",
    country: "United States",
    name: "Newark Liberty International Airport",
    lat: 40.6895,
    lng: -74.1745,
  },

  // Chicago Hubs
  {
    code: "ORD",
    city: "Chicago",
    country: "United States",
    name: "O'Hare International Airport",
    lat: 41.9742,
    lng: -87.9073,
  },
  {
    code: "MDW",
    city: "Chicago",
    country: "United States",
    name: "Midway International Airport",
    lat: 41.7861,
    lng: -87.7521,
  },

  // Major Hubs
  {
    code: "BOS",
    city: "Boston",
    country: "United States",
    name: "Boston Logan International Airport",
    lat: 42.3656,
    lng: -71.0096,
  },
  {
    code: "MCO",
    city: "Orlando",
    country: "United States",
    name: "Orlando International Airport",
    lat: 28.4312,
    lng: -81.3089,
  },
  {
    code: "BNA",
    city: "Nashville",
    country: "United States",
    name: "Nashville International Airport",
    lat: 36.1245,
    lng: -86.6782,
  },
  {
    code: "ATL",
    city: "Atlanta",
    country: "United States",
    name: "Hartsfield-Jackson Atlanta International Airport",
    lat: 33.6407,
    lng: -84.4277,
  },
  {
    code: "MIA",
    city: "Miami",
    country: "United States",
    name: "Miami International Airport",
    lat: 25.7959,
    lng: -80.287,
  },

  // Southeast
  {
    code: "CLT",
    city: "Charlotte",
    country: "United States",
    name: "Charlotte Douglas International Airport",
    lat: 35.214,
    lng: -80.9131,
  },
  {
    code: "RDU",
    city: "Raleigh",
    country: "United States",
    name: "Raleigh-Durham International Airport",
    lat: 35.8776,
    lng: -78.7875,
  },
  {
    code: "RIC",
    city: "Richmond",
    country: "United States",
    name: "Richmond International Airport",
    lat: 37.5245,
    lng: -77.32,
  },
  {
    code: "ORF",
    city: "Norfolk",
    country: "United States",
    name: "Norfolk International Airport",
    lat: 36.8946,
    lng: -76.2012,
  },
  {
    code: "TPA",
    city: "Tampa",
    country: "United States",
    name: "Tampa International Airport",
    lat: 27.9755,
    lng: -82.5338,
  },
  {
    code: "FLL",
    city: "Fort Lauderdale",
    country: "United States",
    name: "Fort Lauderdale-Hollywood International Airport",
    lat: 26.0726,
    lng: -80.1527,
  },
  {
    code: "PBI",
    city: "West Palm Beach",
    country: "United States",
    name: "Palm Beach International Airport",
    lat: 26.6832,
    lng: -80.0956,
  },
  {
    code: "JAX",
    city: "Jacksonville",
    country: "United States",
    name: "Jacksonville International Airport",
    lat: 30.4941,
    lng: -81.6879,
  },
  {
    code: "TLH",
    city: "Tallahassee",
    country: "United States",
    name: "Tallahassee International Airport",
    lat: 30.3963,
    lng: -84.27,
  },
  {
    code: "PNS",
    city: "Pensacola",
    country: "United States",
    name: "Pensacola International Airport",
    lat: 30.4735,
    lng: -87.1868,
  },
  {
    code: "SAV",
    city: "Savannah",
    country: "United States",
    name: "Savannah/Hilton Head International Airport",
    lat: 32.1277,
    lng: -81.201,
  },
  {
    code: "CHS",
    city: "Charleston",
    country: "United States",
    name: "Charleston International Airport",
    lat: 32.8988,
    lng: -80.0408,
  },
  {
    code: "CAE",
    city: "Columbia",
    country: "United States",
    name: "Columbia Metropolitan Airport",
    lat: 34.001,
    lng: -81.1189,
  },
  {
    code: "GSP",
    city: "Greenville",
    country: "United States",
    name: "Greenville-Spartanburg International Airport",
    lat: 34.8954,
    lng: -82.2186,
  },
  {
    code: "TYS",
    city: "Knoxville",
    country: "United States",
    name: "McGhee Tyson Airport",
    lat: 35.8116,
    lng: -83.9411,
  },
  {
    code: "BHM",
    city: "Birmingham",
    country: "United States",
    name: "Birmingham-Shuttlesworth International Airport",
    lat: 33.5629,
    lng: -86.7519,
  },
  {
    code: "MOB",
    city: "Mobile",
    country: "United States",
    name: "Mobile Regional Airport",
    lat: 32.3792,
    lng: -86.6397,
  },
  {
    code: "MSY",
    city: "New Orleans",
    country: "United States",
    name: "Louis Armstrong New Orleans International Airport",
    lat: 29.9844,
    lng: -90.258,
  },
  {
    code: "MEM",
    city: "Memphis",
    country: "United States",
    name: "Memphis International Airport",
    lat: 35.0424,
    lng: -89.9767,
  },

  // Midwest
  {
    code: "DTW",
    city: "Detroit",
    country: "United States",
    name: "Detroit Metropolitan Wayne County Airport",
    lat: 42.2124,
    lng: -83.3534,
  },
  {
    code: "CLE",
    city: "Cleveland",
    country: "United States",
    name: "Cleveland Hopkins International Airport",
    lat: 41.4117,
    lng: -81.8498,
  },
  {
    code: "CMH",
    city: "Columbus",
    country: "United States",
    name: "John Glenn Columbus International Airport",
    lat: 39.998,
    lng: -82.8984,
  },
  {
    code: "CVG",
    city: "Cincinnati",
    country: "United States",
    name: "Cincinnati/Northern Kentucky International Airport",
    lat: 39.0486,
    lng: -84.6677,
  },
  {
    code: "IND",
    city: "Indianapolis",
    country: "United States",
    name: "Indianapolis International Airport",
    lat: 39.7173,
    lng: -86.2944,
  },
  {
    code: "SDF",
    city: "Louisville",
    country: "United States",
    name: "Louisville Muhammad Ali International Airport",
    lat: 38.8521,
    lng: -85.7353,
  },
  {
    code: "PIT",
    city: "Pittsburgh",
    country: "United States",
    name: "Pittsburgh International Airport",
    lat: 40.4914,
    lng: -80.2329,
  },
  {
    code: "MSP",
    city: "Minneapolis",
    country: "United States",
    name: "Minneapolis-St. Paul International Airport",
    lat: 44.882,
    lng: -93.2169,
  },
  {
    code: "MKE",
    city: "Milwaukee",
    country: "United States",
    name: "Milwaukee Mitchell International Airport",
    lat: 42.9471,
    lng: -87.897,
  },
  {
    code: "MSN",
    city: "Madison",
    country: "United States",
    name: "Dane County Regional Airport",
    lat: 43.1399,
    lng: -89.3374,
  },
  {
    code: "GRR",
    city: "Grand Rapids",
    country: "United States",
    name: "Gerald R. Ford International Airport",
    lat: 42.8884,
    lng: -85.5226,
  },
  {
    code: "STL",
    city: "St. Louis",
    country: "United States",
    name: "St. Louis Lambert International Airport",
    lat: 38.7469,
    lng: -90.37,
  },
  {
    code: "MCI",
    city: "Kansas City",
    country: "United States",
    name: "Kansas City International Airport",
    lat: 39.2976,
    lng: -94.7139,
  },
  { code: "OMA", city: "Omaha", country: "United States", name: "Eppley Airfield", lat: 41.3033, lng: -95.894 },
  {
    code: "DSM",
    city: "Des Moines",
    country: "United States",
    name: "Des Moines International Airport",
    lat: 41.5335,
    lng: -93.6667,
  },
  {
    code: "FSD",
    city: "Sioux Falls",
    country: "United States",
    name: "Sioux Falls Regional Airport",
    lat: 43.546,
    lng: -96.7313,
  },
  {
    code: "FAR",
    city: "Fargo",
    country: "United States",
    name: "Hector International Airport",
    lat: 46.9277,
    lng: -96.8357,
  },
  {
    code: "BIS",
    city: "Bismarck",
    country: "United States",
    name: "Bismarck Municipal Airport",
    lat: 46.7684,
    lng: -100.736,
  },
  {
    code: "RAP",
    city: "Rapid City",
    country: "United States",
    name: "Rapid City Regional Airport",
    lat: 43.8495,
    lng: -103.0183,
  },
  {
    code: "ICT",
    city: "Wichita",
    country: "United States",
    name: "Wichita Dwight D. Eisenhower National Airport",
    lat: 37.6502,
    lng: -97.4331,
  },
  {
    code: "LIT",
    city: "Little Rock",
    country: "United States",
    name: "Bill and Hillary Clinton National Airport",
    lat: 34.7299,
    lng: -92.2241,
  },

  // Texas & Southwest
  {
    code: "IAH",
    city: "Houston",
    country: "United States",
    name: "George Bush Intercontinental Airport",
    lat: 29.9902,
    lng: -95.3368,
  },
  { code: "DAL", city: "Dallas", country: "United States", name: "Dallas Love Field", lat: 32.8472, lng: -96.8514 },
  {
    code: "DFW",
    city: "Dallas",
    country: "United States",
    name: "Dallas/Fort Worth International Airport",
    lat: 32.8975,
    lng: -97.0381,
  },
  {
    code: "AUS",
    city: "Austin",
    country: "United States",
    name: "Austin-Bergstrom International Airport",
    lat: 30.1945,
    lng: -97.6699,
  },
  {
    code: "SAT",
    city: "San Antonio",
    country: "United States",
    name: "San Antonio International Airport",
    lat: 29.5337,
    lng: -98.4695,
  },
  {
    code: "TUL",
    city: "Tulsa",
    country: "United States",
    name: "Tulsa International Airport",
    lat: 36.3985,
    lng: -95.8582,
  },
  {
    code: "OKC",
    city: "Oklahoma City",
    country: "United States",
    name: "Will Rogers World Airport",
    lat: 35.3395,
    lng: -97.6005,
  },
  {
    code: "DEN",
    city: "Denver",
    country: "United States",
    name: "Denver International Airport",
    lat: 39.8561,
    lng: -104.6737,
  },
  {
    code: "PHX",
    city: "Phoenix",
    country: "United States",
    name: "Phoenix Sky Harbor International Airport",
    lat: 33.4484,
    lng: -112.074,
  },
  {
    code: "SLC",
    city: "Salt Lake City",
    country: "United States",
    name: "Salt Lake City International Airport",
    lat: 40.7884,
    lng: -111.8787,
  },
  {
    code: "LAS",
    city: "Las Vegas",
    country: "United States",
    name: "Harry Reid International Airport",
    lat: 36.084,
    lng: -115.1537,
  },
  {
    code: "ABQ",
    city: "Albuquerque",
    country: "United States",
    name: "Albuquerque International Sunport",
    lat: 35.0394,
    lng: -106.6365,
  },
  {
    code: "ELP",
    city: "El Paso",
    country: "United States",
    name: "El Paso International Airport",
    lat: 31.8074,
    lng: -106.3779,
  },

  // West Coast
  {
    code: "LAX",
    city: "Los Angeles",
    country: "United States",
    name: "Los Angeles International Airport",
    lat: 33.9425,
    lng: -118.4081,
  },
  {
    code: "SFO",
    city: "San Francisco",
    country: "United States",
    name: "San Francisco International Airport",
    lat: 37.6213,
    lng: -122.379,
  },
  {
    code: "SEA",
    city: "Seattle",
    country: "United States",
    name: "Seattle-Tacoma International Airport",
    lat: 47.4502,
    lng: -122.3088,
  },
  {
    code: "PDX",
    city: "Portland",
    country: "United States",
    name: "Portland International Airport",
    lat: 45.5887,
    lng: -122.5975,
  },
  {
    code: "SAN",
    city: "San Diego",
    country: "United States",
    name: "San Diego International Airport",
    lat: 32.7345,
    lng: -117.1896,
  },

  // Northeast
  {
    code: "PHL",
    city: "Philadelphia",
    country: "United States",
    name: "Philadelphia International Airport",
    lat: 39.8716,
    lng: -75.2411,
  },
  {
    code: "BWI",
    city: "Baltimore",
    country: "United States",
    name: "Baltimore/Washington International Airport",
    lat: 39.1754,
    lng: -76.6684,
  },
  {
    code: "DCA",
    city: "Washington",
    country: "United States",
    name: "Ronald Reagan Washington National Airport",
    lat: 38.8521,
    lng: -77.0377,
  },
  {
    code: "MDT",
    city: "Harrisburg",
    country: "United States",
    name: "Harrisburg International Airport",
    lat: 40.2046,
    lng: -76.8513,
  },
  {
    code: "ALB",
    city: "Albany",
    country: "United States",
    name: "Albany International Airport",
    lat: 42.7484,
    lng: -73.7982,
  },
  {
    code: "BUF",
    city: "Buffalo",
    country: "United States",
    name: "Buffalo Niagara International Airport",
    lat: 42.9405,
    lng: -78.7369,
  },
  {
    code: "ROC",
    city: "Rochester",
    country: "United States",
    name: "Greater Rochester International Airport",
    lat: 43.119,
    lng: -77.6724,
  },
  {
    code: "SYR",
    city: "Syracuse",
    country: "United States",
    name: "Syracuse Hancock International Airport",
    lat: 43.1112,
    lng: -76.106,
  },
  {
    code: "BDL",
    city: "Hartford",
    country: "United States",
    name: "Bradley International Airport",
    lat: 41.9389,
    lng: -72.6834,
  },
  { code: "PVD", city: "Providence", country: "United States", name: "T.F. Green Airport", lat: 41.7242, lng: -71.422 },
  {
    code: "MHT",
    city: "Manchester",
    country: "United States",
    name: "Manchester-Boston Regional Airport",
    lat: 42.9356,
    lng: -71.4352,
  },
  {
    code: "PWM",
    city: "Portland",
    country: "United States",
    name: "Portland International Jetport",
    lat: 43.6461,
    lng: -70.3083,
  },
  {
    code: "BTV",
    city: "Burlington",
    country: "United States",
    name: "Burlington International Airport",
    lat: 44.4704,
    lng: -73.1505,
  },
  {
    code: "BGR",
    city: "Bangor",
    country: "United States",
    name: "Bangor International Airport",
    lat: 44.8074,
    lng: -68.8281,
  },

  // International - Italy
  {
    code: "FCO",
    city: "Rome",
    country: "Italy",
    name: "Leonardo da Vinci-Fiumicino Airport",
    lat: 41.8002,
    lng: 12.2388,
  },
  { code: "SUF", city: "Lamezia Terme", country: "Italy", name: "Lamezia Terme Airport", lat: 38.9067, lng: 16.2419 },
  { code: "MXP", city: "Milan", country: "Italy", name: "Milan Malpensa Airport", lat: 45.6306, lng: 8.7281 },
  { code: "LIN", city: "Milan", country: "Italy", name: "Milan Linate Airport", lat: 45.4626, lng: 9.2119 },
  { code: "VCE", city: "Venice", country: "Italy", name: "Venice Marco Polo Airport", lat: 45.5052, lng: 12.3519 },
  {
    code: "BLQ",
    city: "Bologna",
    country: "Italy",
    name: "Bologna Guglielmo Marconi Airport",
    lat: 44.5351,
    lng: 11.2889,
  },
  { code: "CIA", city: "Rome", country: "Italy", name: "Rome Ciampino Airport", lat: 41.7994, lng: 12.5949 },

  // International - Europe
  { code: "CDG", city: "Paris", country: "France", name: "Paris Charles de Gaulle Airport", lat: 49.0097, lng: 2.5479 },
  { code: "ORY", city: "Paris", country: "France", name: "Paris Orly Airport", lat: 48.7225, lng: 2.3592 },
  {
    code: "MAD",
    city: "Madrid",
    country: "Spain",
    name: "Adolfo Suárez Madrid-Barajas Airport",
    lat: 40.4719,
    lng: -3.5625,
  },
  { code: "BCN", city: "Barcelona", country: "Spain", name: "Barcelona-El Prat Airport", lat: 41.2974, lng: 2.0833 },

  // International - Middle East
  {
    code: "OMDW",
    city: "Dubai",
    country: "United Arab Emirates",
    name: "Al Maktoum International Airport",
    lat: 24.9454,
    lng: 55.1695,
  },
  {
    code: "DXB",
    city: "Dubai",
    country: "United Arab Emirates",
    name: "Dubai International Airport",
    lat: 25.2528,
    lng: 55.3644,
  },

  // International - Caribbean
  {
    code: "AUA",
    city: "Oranjestad",
    country: "Aruba",
    name: "Queen Beatrix International Airport",
    lat: 12.1844,
    lng: -68.9528,
  },
  {
    code: "SVD",
    city: "Kingstown",
    country: "St. Vincent",
    name: "Argyle International Airport",
    lat: 13.145,
    lng: -61.205,
  },
  {
    code: "SXM",
    city: "Philipsburg",
    country: "St. Martin",
    name: "Princess Juliana International Airport",
    lat: 18.0424,
    lng: -63.1087,
  },
]

export type Airport = (typeof airports)[0]
